### ISSUE TITLE
Error while install modules

### ISSUE THREAD

**Issue by wireinet** [axecopfire/Sassy_Pug_Stack#12]
npm ERR!
npm ERR!
npm ERR!
and so on...
very sad...it thought i finded ideal gulp-build ))

For example:
npm ERR! gyp verb `which` failed
npm ERR! gyp ERR! stack

**Comment by axecopfire** [comment]
Fixed 
https://github.com/axecopfire/Sassy_Pug_Stack/commit/742a8108b4b0e9458c60a660af0eca59d2b18497
